# This is a basic workflow to help you get started with Actions

name: CICD

on:
  push:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: dev
    steps:  
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}          
      - name: 'Run az commands'
        run: |
          az account show
          az group list
          pwd
